export const GOVERNANCE_CORE_VERSION = "15.20";
export const GOVERNANCE_PIPELINE_VERSION =
  `governance-v${GOVERNANCE_CORE_VERSION}-final-audit-closure`;
export const GOVERNANCE_RESULT_SNAPSHOT_VERSION = GOVERNANCE_CORE_VERSION;
